version: '3.2'

services:
  database:
    container_name: nx-fullstack-database
    image: postgres:latest
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASS}
